### ISSUE TITLE
[crash] RaDecVal.fits

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/old-carta-backend#69]
Debug: CasaImageLoader plugin trying to load image:  "/Users/kswang/CARTA/Images/carta_image_library/Images/RaDecVel.fits"
Debug: CasaImageLoader plugin tries to load non-casa image
Debug: 	-opened as FITS image
Debug: lat.shape =  [3, 4, 7, 1]
Debug: lat.dataType =  7
Debug: Float type is  7
[1m[31mFatal: ASSERT: "uint(i) < uint(size())" in file /usr/local/Cellar/qt@5.7/5.7.1/lib/QtCore.framework/Headers/qstring.h, line 879 ((null):0, (null))[0m

**Comment by duidae** [comment]
dead point:
int stokeIndicator = Util::getAxisIndex(image, AxisInfo::KnownType::STOKES);  // DataLoader.cpp std::shared_ptr<CoordinateFormatterInterface> cf(
                               image-> metaData()-> coordinateFormatter()-> clone() ); // Util.cpp
image-> metaData() -> coordinateFormatter() <- 這個就掛了

std::make_shared < CCCoordinateFormatter > ( m_casaCS );

CCCoordinateFormatter::parseCasaCSi( int pixelAxis )

parseCasaCSi裡會把axis label第一個字元轉大寫, 但沒檢查axis label是不是空的, 空字串導致crash

fixed in commit 4e766ab

**Comment by kswang1029** [comment]
believe it or not, with the desktop version I can open this image without problems.
